### ISSUE TITLE
How to obtain an unpadded image

### ISSUE THREAD

**Issue by anganiang** [malidib/Craters_MaskRCNN#2]
Hello, I have read your paper, but I have a question. I would like to know how to convert an area with a width and height approximately twice the required size of 512x512 pixels into a rectilinear projection, and then crop the central 512x512 pixels to obtain an unpadded image.

**Comment by malidib** [comment]
Please check https://arxiv.org/abs/1803.02192 and the associated codes.

**Comment by anganiang** [comment]
I know, but DeepMoon’s steps are to downsample the image to 256*256 first and then perform projection conversion. Is your method to perform projection conversion first and then directly crop the 512*512 area?
